// DoodleRun — the slot table: canvas sizes, categories and every drawable slot.

export const CANVAS = {
  tile: { w: 64, h: 64 },
  creature: { w: 96, h: 96 },
  backdrop: { w: 512, h: 160 },
  hero: { w: 96, h: 96 },
};

export const CATEGORIES = [
  { id: 'terrain', name: 'Terrain' },
  { id: 'hazard', name: 'Hazards' },
  { id: 'creature', name: 'Creatures' },
  { id: 'loot', name: 'Loot' },
  { id: 'backdrop', name: 'Backdrop' },
  { id: 'effect', name: 'Moments' },
  { id: 'music', name: 'Soundtrack' },
  { id: 'hero', name: 'Your hero' },
];

// The twelve the world cannot start without. Everything else is optional:
// a room can run before it is drawn, and my scribble stands in until it is.
export const CORE = [
  'ground', 'platform', 'spikes', 'walker', 'flyer', 'jumper',
  'crawler', 'charger', 'guard', 'coin', 'shield', 'sky',
];

export const SLOTS = [
  {
    id: 'ground',
    name: 'Block',
    hint: 'A solid block of ground. Fill every pixel — the runner stands on this and it tiles in every direction.',
    category: 'terrain',
    width: CANVAS.tile.w,
    height: CANVAS.tile.h,
    requiresFullCoverage: true,
    sound: false,
    defaultBehaviour: 'none',
    behaviours: [],
    tempo: 1,
    shared: true,
  },
  {
    id: 'platform',
    name: 'Platform',
    hint: 'A floating platform. Copies sit side by side to make longer ledges, so keep the left and right edges solid.',
    category: 'terrain',
    width: CANVAS.tile.w,
    height: CANVAS.tile.h,
    requiresFullCoverage: false,
    sound: false,
    defaultBehaviour: 'none',
    behaviours: [],
    tempo: 1,
    shared: true,
  },
  {
    id: 'spikes',
    name: 'Spikes',
    hint: 'Deadly spikes. Draw the points however you like — gaps between them are the whole idea. Touching this ends the run for everyone.',
    category: 'hazard',
    width: CANVAS.tile.w,
    height: CANVAS.tile.h,
    requiresFullCoverage: false,
    sound: false,
    defaultBehaviour: 'none',
    behaviours: [],
    tempo: 1,
    shared: true,
  },
  {
    id: 'walker',
    name: 'Walker',
    hint: 'A creature that walks toward you along the ground. Two legs, a body and a head make it move.',
    category: 'creature',
    width: CANVAS.creature.w,
    height: CANVAS.creature.h,
    requiresFullCoverage: false,
    sound: true,
    defaultBehaviour: 'walk',
    behaviours: ['walk', 'fly', 'jump'],
    tempo: 1,
    shared: true,
  },
  {
    id: 'flyer',
    name: 'Flyer',
    hint: 'A creature that flies at head height. Two wings and a body make it flap.',
    category: 'creature',
    width: CANVAS.creature.w,
    height: CANVAS.creature.h,
    requiresFullCoverage: false,
    sound: true,
    defaultBehaviour: 'fly',
    behaviours: ['fly', 'walk', 'jump'],
    tempo: 1,
    shared: true,
  },
  {
    id: 'jumper',
    name: 'Hopper',
    hint: 'A creature that hops along the ground. Two legs and a body make it bounce.',
    category: 'creature',
    width: CANVAS.creature.w,
    height: CANVAS.creature.h,
    requiresFullCoverage: false,
    sound: true,
    defaultBehaviour: 'jump',
    behaviours: ['jump', 'walk', 'fly'],
    tempo: 1,
    shared: true,
  },
  {
    id: 'crawler',
    name: 'Ceiling crawler',
    hint: 'A creature that crawls upside down along ceilings. Draw it upright; the game hangs it from the ceiling.',
    category: 'creature',
    width: CANVAS.creature.w,
    height: CANVAS.creature.h,
    requiresFullCoverage: false,
    sound: true,
    defaultBehaviour: 'walk',
    behaviours: ['walk', 'fly', 'jump'],
    tempo: 0.8,
    shared: true,
  },
  {
    id: 'charger',
    name: 'Charger',
    hint: 'A creature that sprints at you the moment it sees you. Same rig as a walker, just angrier.',
    category: 'creature',
    width: CANVAS.creature.w,
    height: CANVAS.creature.h,
    requiresFullCoverage: false,
    sound: true,
    defaultBehaviour: 'walk',
    behaviours: ['walk', 'fly', 'jump'],
    tempo: 1.8,
    shared: true,
  },
  {
    id: 'guard',
    name: 'Guard',
    hint: 'A creature that stands still and blocks the way. It only needs a body; add a head for a nod.',
    category: 'creature',
    width: CANVAS.creature.w,
    height: CANVAS.creature.h,
    requiresFullCoverage: false,
    sound: true,
    defaultBehaviour: 'idle',
    behaviours: ['idle', 'walk', 'fly', 'jump'],
    tempo: 1,
    shared: true,
  },
  {
    id: 'coin',
    name: 'Coin',
    hint: 'A coin worth ten points. Place the spin axis and it twirls in place.',
    category: 'loot',
    width: CANVAS.tile.w,
    height: CANVAS.tile.h,
    requiresFullCoverage: false,
    sound: true,
    defaultBehaviour: 'spin',
    behaviours: ['spin', 'idle'],
    tempo: 1,
    shared: true,
  },
  {
    id: 'shield',
    name: 'Shield',
    hint: 'A one-hit shield pickup. Give it a spin axis, or let it hover with a body point.',
    category: 'loot',
    width: CANVAS.tile.w,
    height: CANVAS.tile.h,
    requiresFullCoverage: false,
    sound: true,
    defaultBehaviour: 'spin',
    behaviours: ['spin', 'idle'],
    tempo: 0.7,
    shared: true,
  },
  {
    id: 'luckyBlock',
    name: 'Lucky block',
    hint: 'A block with something inside. Hit it from underneath and it gives up coins — or a power. Draw it so it looks worth headbutting.',
    category: 'terrain',
    width: CANVAS.tile.w,
    height: CANVAS.tile.h,
    requiresFullCoverage: false,
    sound: true,
    defaultBehaviour: 'none',
    behaviours: [],
    tempo: 1,
    shared: true,
  },
  {
    id: 'trampoline',
    name: 'Trampoline',
    hint: 'Land on this and you are thrown far higher than you can jump. Draw something that looks springy.',
    category: 'terrain',
    width: CANVAS.tile.w,
    height: CANVAS.tile.h,
    requiresFullCoverage: false,
    sound: true,
    defaultBehaviour: 'none',
    behaviours: [],
    tempo: 1,
    shared: true,
  },
  {
    id: 'mover',
    name: 'Moving platform',
    hint: 'A platform that slides up and down on its own. You have to time it, and you ride it while you stand on it.',
    category: 'terrain',
    width: CANVAS.tile.w,
    height: CANVAS.tile.h,
    requiresFullCoverage: false,
    sound: true,
    defaultBehaviour: 'none',
    behaviours: [],
    tempo: 1,
    shared: true,
  },
  {
    id: 'conveyor',
    name: 'Conveyor',
    hint: 'A belt that speeds you up or drags you back, depending on which way it is laid. Draw an arrow so the direction reads at a glance.',
    category: 'terrain',
    width: CANVAS.tile.w,
    height: CANVAS.tile.h,
    requiresFullCoverage: false,
    sound: true,
    defaultBehaviour: 'none',
    behaviours: [],
    tempo: 1,
    shared: true,
  },
  {
    id: 'saw',
    name: 'Saw blade',
    hint: 'A blade that slides back and forth along the ground. Give it a spin axis so it turns while it travels.',
    category: 'hazard',
    width: CANVAS.creature.w,
    height: CANVAS.creature.h,
    requiresFullCoverage: false,
    sound: true,
    defaultBehaviour: 'spin',
    behaviours: ['spin', 'idle'],
    tempo: 1.6,
    shared: true,
  },
  {
    id: 'rock',
    name: 'Falling rock',
    hint: 'It hangs above the track and drops the moment you run underneath. Draw it heavy.',
    category: 'hazard',
    width: CANVAS.creature.w,
    height: CANVAS.creature.h,
    requiresFullCoverage: false,
    sound: true,
    defaultBehaviour: 'idle',
    behaviours: ['idle', 'spin'],
    tempo: 1,
    shared: true,
  },
  {
    id: 'fire',
    name: 'Pit fire',
    hint: 'What waits at the bottom of every gap. Draw it so a hole in the ground looks like a bad idea.',
    category: 'hazard',
    width: CANVAS.tile.w,
    height: CANVAS.tile.h,
    requiresFullCoverage: false,
    sound: true,
    defaultBehaviour: 'none',
    behaviours: [],
    tempo: 1,
    shared: true,
  },
  {
    id: 'chaser',
    name: 'The chaser',
    hint: 'It only wakes up when you slow down, and then it comes for you from behind. Draw something you would not want catching up.',
    category: 'creature',
    width: CANVAS.creature.w,
    height: CANVAS.creature.h,
    requiresFullCoverage: false,
    sound: true,
    defaultBehaviour: 'fly',
    behaviours: ['fly', 'walk', 'jump'],
    tempo: 1.3,
    shared: true,
  },
  {
    id: 'magnet',
    name: 'Magnet',
    hint: 'Pick it up and coins fly to you for a few seconds.',
    category: 'loot',
    width: CANVAS.tile.w,
    height: CANVAS.tile.h,
    requiresFullCoverage: false,
    sound: true,
    defaultBehaviour: 'spin',
    behaviours: ['spin', 'idle'],
    tempo: 1,
    shared: true,
  },
  {
    id: 'clock',
    name: 'Clock',
    hint: 'Pick it up and the whole world slows down for a moment, which is usually the difference between dying and not.',
    category: 'loot',
    width: CANVAS.tile.w,
    height: CANVAS.tile.h,
    requiresFullCoverage: false,
    sound: true,
    defaultBehaviour: 'spin',
    behaviours: ['spin', 'idle'],
    tempo: 0.8,
    shared: true,
  },
  {
    id: 'heart',
    name: 'Heart',
    hint: 'One extra life for the whole team: the next death picks you straight back up instead of sending everybody to the start.',
    category: 'loot',
    width: CANVAS.tile.w,
    height: CANVAS.tile.h,
    requiresFullCoverage: false,
    sound: true,
    defaultBehaviour: 'idle',
    behaviours: ['idle', 'spin'],
    tempo: 1,
    shared: true,
  },
  {
    id: 'gate',
    name: 'Checkpoint gate',
    hint: 'A gate every thousand metres. Run through it and that is where you all restart from, instead of the beginning.',
    category: 'effect',
    width: CANVAS.creature.w,
    height: CANVAS.creature.h,
    requiresFullCoverage: false,
    sound: true,
    defaultBehaviour: 'idle',
    behaviours: ['idle', 'spin'],
    tempo: 1,
    shared: true,
  },
  {
    id: 'sparkle',
    name: 'Coin sparkle',
    hint: 'The little burst that pops where a coin was. Draw it small and bright.',
    category: 'effect',
    width: CANVAS.tile.w,
    height: CANVAS.tile.h,
    requiresFullCoverage: false,
    sound: false,
    defaultBehaviour: 'spin',
    behaviours: ['spin', 'idle'],
    tempo: 2,
    shared: true,
  },
  {
    id: 'sky',
    name: 'Sky',
    hint: 'Everything behind the world. It fills the whole screen and never scrolls, so keep it calm — your characters have to stand out against it.',
    category: 'backdrop',
    width: CANVAS.backdrop.w,
    height: CANVAS.backdrop.h,
    requiresFullCoverage: false,
    sound: false,
    defaultBehaviour: 'none',
    behaviours: [],
    tempo: 1,
    shared: true,
  },
  {
    id: 'drums',
    name: 'Drums',
    hint: 'The beat everything else sits on. Beatbox it, tap the table, clap — just keep it steady.',
    category: 'music',
    music: true,
    width: CANVAS.tile.w,
    height: CANVAS.tile.h,
    requiresFullCoverage: false,
    sound: false,
    defaultBehaviour: 'none',
    behaviours: [],
    tempo: 1,
    shared: true,
  },
  {
    id: 'bass',
    name: 'Bass',
    hint: 'The low part. Hum two or three long notes; this is the floor the song stands on.',
    category: 'music',
    music: true,
    width: CANVAS.tile.w,
    height: CANVAS.tile.h,
    requiresFullCoverage: false,
    sound: false,
    defaultBehaviour: 'none',
    behaviours: [],
    tempo: 1,
    shared: true,
  },
  {
    id: 'chords',
    name: 'Chords',
    hint: 'The background. Play a piano into the mic if you have one, or hum long notes underneath.',
    category: 'music',
    music: true,
    width: CANVAS.tile.w,
    height: CANVAS.tile.h,
    requiresFullCoverage: false,
    sound: false,
    defaultBehaviour: 'none',
    behaviours: [],
    tempo: 1,
    shared: true,
  },
  {
    id: 'melody',
    name: 'Melody',
    hint: 'The bit people hum afterwards. Sing it over the top of everything else.',
    category: 'music',
    music: true,
    width: CANVAS.tile.w,
    height: CANVAS.tile.h,
    requiresFullCoverage: false,
    sound: false,
    defaultBehaviour: 'none',
    behaviours: [],
    tempo: 1,
    shared: true,
  },
  {
    id: 'free',
    name: 'Anything',
    hint: 'Whatever you want on top: a shout, a whistle, a weird noise, a second melody.',
    category: 'music',
    music: true,
    width: CANVAS.tile.w,
    height: CANVAS.tile.h,
    requiresFullCoverage: false,
    sound: false,
    defaultBehaviour: 'none',
    behaviours: [],
    tempo: 1,
    shared: true,
  },
  {
    id: 'hero',
    name: 'Your hero',
    hint: 'Your own runner. Two legs, a body and a head — this one is you and it is not shared.',
    category: 'hero',
    width: CANVAS.hero.w,
    height: CANVAS.hero.h,
    requiresFullCoverage: false,
    sound: true,
    defaultBehaviour: 'walk',
    behaviours: ['walk', 'jump'],
    tempo: 1,
    shared: false,
  },
];

export const SLOT_BY_ID = Object.fromEntries(SLOTS.map((s) => [s.id, s]));

export const MUSIC_SLOTS = ['drums', 'bass', 'chords', 'melody', 'free'];

export function slotsByCategory(categoryId) {
  return SLOTS.filter((s) => s.category === categoryId);
}
