// DoodleRun — the slot table: canvas sizes, categories and every drawable slot.

export const CANVAS = {
  tile: { w: 64, h: 64 },
  creature: { w: 96, h: 96 },
  backdrop: { w: 512, h: 160 },
  hero: { w: 96, h: 96 },
};

export const CATEGORIES = [
  { id: 'terrain', name: 'Terrain' },
  { id: 'creature', name: 'Creatures' },
  { id: 'loot', name: 'Loot' },
  { id: 'backdrop', name: 'Backdrop' },
  { id: 'hero', name: 'Your hero' },
];

export const SLOTS = [
  {
    id: 'ground',
    name: 'Block',
    hint: 'A solid block of ground. Fill every pixel — the runner stands on this and it tiles in every direction.',
    category: 'terrain',
    width: CANVAS.tile.w,
    height: CANVAS.tile.h,
    requiresFullCoverage: true,
    defaultBehaviour: 'none',
    behaviours: [],
    tempo: 1,
    shared: true,
  },
  {
    id: 'platform',
    name: 'Platform',
    hint: 'A floating platform. Fill every pixel; copies sit side by side to make longer ledges.',
    category: 'terrain',
    width: CANVAS.tile.w,
    height: CANVAS.tile.h,
    requiresFullCoverage: true,
    defaultBehaviour: 'none',
    behaviours: [],
    tempo: 1,
    shared: true,
  },
  {
    id: 'spikes',
    name: 'Spikes',
    hint: 'Deadly spikes. Fill every pixel; touching this tile ends the run for everyone.',
    category: 'terrain',
    width: CANVAS.tile.w,
    height: CANVAS.tile.h,
    requiresFullCoverage: true,
    defaultBehaviour: 'none',
    behaviours: [],
    tempo: 1,
    shared: true,
  },
  {
    id: 'walker',
    name: 'Walker',
    hint: 'A creature that walks toward you along the ground. Two legs, a body and a head make it move.',
    category: 'creature',
    width: CANVAS.creature.w,
    height: CANVAS.creature.h,
    requiresFullCoverage: false,
    defaultBehaviour: 'walk',
    behaviours: ['walk', 'fly', 'jump'],
    tempo: 1,
    shared: true,
  },
  {
    id: 'flyer',
    name: 'Flyer',
    hint: 'A creature that flies at head height. Two wings and a body make it flap.',
    category: 'creature',
    width: CANVAS.creature.w,
    height: CANVAS.creature.h,
    requiresFullCoverage: false,
    defaultBehaviour: 'fly',
    behaviours: ['fly', 'walk', 'jump'],
    tempo: 1,
    shared: true,
  },
  {
    id: 'jumper',
    name: 'Hopper',
    hint: 'A creature that hops along the ground. Two legs and a body make it bounce.',
    category: 'creature',
    width: CANVAS.creature.w,
    height: CANVAS.creature.h,
    requiresFullCoverage: false,
    defaultBehaviour: 'jump',
    behaviours: ['jump', 'walk', 'fly'],
    tempo: 1,
    shared: true,
  },
  {
    id: 'crawler',
    name: 'Ceiling crawler',
    hint: 'A creature that crawls upside down along ceilings. Draw it upright; the game hangs it from the ceiling.',
    category: 'creature',
    width: CANVAS.creature.w,
    height: CANVAS.creature.h,
    requiresFullCoverage: false,
    defaultBehaviour: 'walk',
    behaviours: ['walk', 'fly', 'jump'],
    tempo: 0.8,
    shared: true,
  },
  {
    id: 'charger',
    name: 'Charger',
    hint: 'A creature that sprints at you the moment it sees you. Same rig as a walker, just angrier.',
    category: 'creature',
    width: CANVAS.creature.w,
    height: CANVAS.creature.h,
    requiresFullCoverage: false,
    defaultBehaviour: 'walk',
    behaviours: ['walk', 'fly', 'jump'],
    tempo: 1.8,
    shared: true,
  },
  {
    id: 'guard',
    name: 'Guard',
    hint: 'A creature that stands still and blocks the way. It only needs a body; add a head for a nod.',
    category: 'creature',
    width: CANVAS.creature.w,
    height: CANVAS.creature.h,
    requiresFullCoverage: false,
    defaultBehaviour: 'idle',
    behaviours: ['idle', 'walk', 'fly', 'jump'],
    tempo: 1,
    shared: true,
  },
  {
    id: 'coin',
    name: 'Coin',
    hint: 'A coin worth ten points. Place the spin axis and it twirls in place.',
    category: 'loot',
    width: CANVAS.tile.w,
    height: CANVAS.tile.h,
    requiresFullCoverage: false,
    defaultBehaviour: 'spin',
    behaviours: ['spin', 'idle'],
    tempo: 1,
    shared: true,
  },
  {
    id: 'shield',
    name: 'Shield',
    hint: 'A one-hit shield pickup. Give it a spin axis, or let it hover with a body point.',
    category: 'loot',
    width: CANVAS.tile.w,
    height: CANVAS.tile.h,
    requiresFullCoverage: false,
    defaultBehaviour: 'spin',
    behaviours: ['spin', 'idle'],
    tempo: 0.7,
    shared: true,
  },
  {
    id: 'sky',
    name: 'Sky',
    hint: 'The sky behind everything. It stretches to the screen and never scrolls. Gaps show white paper.',
    category: 'backdrop',
    width: CANVAS.backdrop.w,
    height: CANVAS.backdrop.h,
    requiresFullCoverage: false,
    defaultBehaviour: 'none',
    behaviours: [],
    tempo: 1,
    shared: true,
  },
  {
    id: 'far',
    name: 'Far layer',
    hint: 'Distant hills, clouds or towers. Scrolls slowly. Leave gaps so the sky shows through.',
    category: 'backdrop',
    width: CANVAS.backdrop.w,
    height: CANVAS.backdrop.h,
    requiresFullCoverage: false,
    defaultBehaviour: 'none',
    behaviours: [],
    tempo: 1,
    shared: true,
  },
  {
    id: 'near',
    name: 'Near layer',
    hint: 'Bushes, fences, signs — whatever sits just behind the track. Scrolls fast. Leave gaps.',
    category: 'backdrop',
    width: CANVAS.backdrop.w,
    height: CANVAS.backdrop.h,
    requiresFullCoverage: false,
    defaultBehaviour: 'none',
    behaviours: [],
    tempo: 1,
    shared: true,
  },
  {
    id: 'hero',
    name: 'Your hero',
    hint: 'Your own runner. Two legs, a body and a head — this one is you and it is not shared.',
    category: 'hero',
    width: CANVAS.hero.w,
    height: CANVAS.hero.h,
    requiresFullCoverage: false,
    defaultBehaviour: 'walk',
    behaviours: ['walk', 'jump'],
    tempo: 1,
    shared: false,
  },
];

export const SLOT_BY_ID = Object.fromEntries(SLOTS.map((s) => [s.id, s]));

export function slotsByCategory(categoryId) {
  return SLOTS.filter((s) => s.category === categoryId);
}
