// DoodleRun — shell design tokens, timings, tuning constants and every user-visible string.

export const SHELL = {
  color: {
    ink: '#000000',
    paper: '#FFFFFF',
    ground: '#E7E0FF',
    hatch: '#E2E0DB',
    edge: '#C9C6C0',
    mute: '#8E8B85',
    muteInv: '#A8A5A0',
    disabled: '#B5B2AC',
    shadow: '#000000',
    alert: '#E5231B',
    alertInk: '#FFFFFF',
    sun: '#FFD400',
    done: '#12C46B',
  },
  border: { b1: '2px', b2: '3px', b3: '4px', b4: '6px' },
  offset: { off1: '3px', off2: '5px', off3: '8px', off4: '12px' },
  radius: '0',
  gap: { xs: '6px', s: '10px', m: '16px', l: '24px', xl: '40px' },
  pad: '20px',
  face: {
    display: 'ui-sans-serif, -apple-system, BlinkMacSystemFont, "Helvetica Neue", Helvetica, Arial, sans-serif',
    mono: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", monospace',
  },
  type: {
    mega: 'clamp(56px,8vw,104px)/.84',
    h1: '40px/.95',
    h2: '26px/1.05',
    h3: '18px/1.15',
    body: '15px/1.5',
    label: '12px/1.2',
    micro: '10px/1.2',
    num: '20px/1',
  },
  track: {
    mega: '-0.03em',
    h1: '-0.02em',
    h2: '-0.01em',
    h3: '0',
    label: '0.18em',
    micro: '0.22em',
  },
  ease: {
    out: 'cubic-bezier(.2,.9,.25,1)',
    snap: 'cubic-bezier(.16,1,.3,1)',
    in: 'cubic-bezier(.6,0,.9,.3)',
    pop: 'cubic-bezier(.34,1.4,.5,1)',
  },
  dur: { tap: '100ms', fast: '140ms', base: '200ms', exit: '160ms', screen: '280ms', land: '360ms' },
  checker: 'repeating-conic-gradient(var(--dr-hatch) 0% 25%, var(--dr-paper) 0% 50%) 0 0/12px 12px',
  minWidth: 960,
};

export const SCREENS = {
  fadeMs: 160,
  itemStaggerMs: 40,
  navDelayMs: 80,
  navStaggerMs: 45,
  rowDelayMs: 60,
  rowStaggerMs: 55,
  landMs: 360,
};

export const EDITOR = {
  canvasMaxWidth: 1040,
  canvasMaxHeight: 520,
  brushSizes: [1, 2, 4, 8],
  defaultSizeIndex: 2,
  brushRange: { min: 1, max: 48 },
  pixelRange: { min: 1, max: 12 },
  defaultColor: '#111111',
  defaultSecondary: '#ffffff',
  recentSwatches: 8,
  pixelCell: 4,
  historyLimit: 20,
  alphaThreshold: 8,
  fillTolerance: 48,
  ghostAlpha: 0.14,
  holeFlashMs: 900,
  holeFlashCount: 3,
  ringClusterThreshold: 40,
  confirmMs: 3200,
  coverageSegments: 20,
};

export const MESH = { cols: 12, rows: 12, fallbackCols: 8, fallbackRows: 8, minFps: 45, fpsWindow: 120, clipExpand: 0.35 };

export const PREVIEW = { size: 260, scale: 2, groundLine: true };

export const AUDIO = { maxMs: 1500, mimeTypes: ['audio/webm;codecs=opus', 'audio/webm', 'audio/mp4'], meterSegments: 20 };

export const BACKDROP = { farSpeed: 18, nearSpeed: 60, groundSpeed: 120, creatureCount: 6, spawnGapPx: 220, bandTop: 0.52, groundLine: 0.72, bandBottom: 0.92 };

export const KEYS = {
  undo: 'KeyZ',
  redo: 'KeyY',
  sizeDown: 'BracketLeft',
  sizeUp: 'BracketRight',
  swap: 'KeyX',
  brush: 'KeyB',
  eraser: 'KeyE',
  fill: 'KeyG',
  picker: 'KeyI',
  mirror: 'KeyM',
  pixel: 'KeyP',
  exit: 'Escape',
  holes: 'KeyH',
  ghost: 'KeyQ',
  resetColors: 'KeyD',
  clear: 'Backspace',
  tabDraw: 'Digit1',
  tabRig: 'Digit2',
  tabSound: 'Digit3',
  armNext: 'KeyA',
  mesh: 'KeyW',
  record: 'KeyR',
  playPause: 'Space',
  confirm: 'Enter',
  hero: 'KeyH',
  help: 'Slash',
};

export const COPY = {
  app: {
    name: 'DoodleRun',
    desktopTitle: 'DoodleRun needs a desktop window',
    desktopNote: 'Open this on a screen at least 960 pixels wide, with a mouse or a trackpad.',
    editorLoading: 'Editor loading…',
    editorLoadingNote: 'Press Esc to go back to the slots.',
  },
  menu: {
    titleA: 'Doodle',
    titleB: 'Run',
    tagline: 'Draw the whole world first. Then rig it. Then run it.',
    nav: [
      { id: 'new', idx: '01', label: 'New set', note: 'Start a fresh world of 15 drawings' },
      { id: 'continue', idx: '02', label: 'Continue', note: 'Pick up the set you were drawing', noteOff: 'Nothing drawn yet' },
      { id: 'how', idx: '03', label: 'How it works', note: 'Draw, rig, run — in 40 seconds' },
      { id: 'demo', idx: '04', label: 'Demo set', note: 'Open my hand-drawn set and poke at it', noteOff: 'Demo set is still loading' },
    ],
    panelTitle: 'How it works',
    steps: [
      ['1 — Draw.', 'Fifteen slots make a world: three ground tiles, six creatures, two pickups, three backdrop layers, and your own character. Open a slot and paint it.'],
      ['2 — Rig.', 'Drop labelled points on your drawing — left leg, right leg, head, wings. The drawing becomes a rubber sheet and the points pull the pixels around them. Nothing is ever cut apart.'],
      ['3 — Run.', 'Not in this build. v1 stops at the animation preview, which is the part worth getting right first.'],
    ],
    panelFoot: 'Ground tiles must cover 100% of the canvas. Holes in a tile are holes in the world.',
    footer: ['DoodleRun v1', 'Desktop only', 'Mouse / trackpad'],
  },
  board: {
    back: '← Menu',
    title: 'Slots',
    sub: 'Fifteen drawings make a world. Draw as many as you like — the rest run on my scribbles.',
    skip: 'Skip to slots',
    heroLabel: 'Your character — required',
    heroLedger: '01 / 01 · This one is yours',
    heroEmptyState: 'Empty — the runner is you',
    heroDraw: 'Draw',
    heroEdit: 'Edit',
    groups: {
      terrain: { name: 'Terrain', count: '3 slots · 100% coverage required' },
      creature: { name: 'Creatures', count: '6 slots' },
      loot: { name: 'Loot', count: '2 slots' },
      backdrop: { name: 'Backdrop', count: '3 slots' },
    },
    notes: {
      ground: 'Solid ground',
      platform: 'Stand on top only',
      spikes: 'Kills on touch',
      walker: 'Walks the floor',
      flyer: 'Flies a sine path',
      jumper: 'Hops toward you',
      crawler: 'Crawls upside down',
      charger: 'Rushes when seen',
      guard: 'Stands still',
      coin: '+1 point',
      shield: 'Take one hit',
      sky: 'No scroll',
      far: 'Scrolls 0.25×',
      near: 'Scrolls 0.55×',
      hero: 'This one is you',
    },
    stateEmpty: 'Empty',
    stateProgress: 'In progress',
    stateDone: 'Done',
    chipRigged: 'Rigged',
    chipSound: 'Sound',
    drawn: (done, total) => `${done} / ${total} drawn`,
    rigged: (n) => `${n} rigged`,
    sound: (n) => `${n} sound`,
    progressPercent: (pct) => `${pct}%`,
    progressStrokes: (n) => `${n} ${n === 1 ? 'stroke' : 'strokes'}`,
    start: 'Start set',
    consequenceAll: 'Everything is yours',
    consequenceSome: (n) => `${n} ${n === 1 ? 'slot' : 'slots'} will use my scribbles`,
    consequenceNone: 'The whole set will use my scribbles',
    summaryTitle: 'Your set',
    summaryLine: 'The run lands in v2. For now, this is the world you made.',
    summaryBack: 'Back to slots',
    summaryMenu: 'Menu',
    cardAria: (name, group, index, count, state) => `${name}, ${group} slot ${index} of ${count}, ${state}`,
  },
  editor: {
    back: '← Esc  Slots',
    saved: 'Saved as you draw',
    done: 'Done',
    tabs: { draw: 'Draw', rig: 'Rig', sound: 'Sound' },
    spec: (w, h, note) => `${w} × ${h} · ${note}`,
    colour: 'Colour',
    recent: 'Recent',
    swap: 'Swap  X',
    brush: 'Brush',
    brushValue: (px) => `${px} px`,
    brushCells: (cells) => `${cells} ${cells === 1 ? 'cell' : 'cells'}`,
    grid: 'Grid',
    gridFree: 'Free',
    gridPixel: 'Pixel',
    gridWorking: (w, h, cell) => `Working grid: ${w} × ${h} · 1 cell = ${cell} px`,
    gridNote: 'Same drawing, chunkier tool. Nothing already painted changes.',
    ghost: 'Ghost hero',
    ghostNote: 'Your character, at true size, for scale.',
    coverage: 'Coverage',
    coverageShort: (n) => `${n} ${n === 1 ? 'pixel' : 'pixels'} still empty. Ground tiles must be solid.`,
    coverageFull: 'Solid. No holes.',
    coverageFree: 'Nothing to fill — this one can have gaps.',
    coverageHoles: (n) => `${n} ${n === 1 ? 'hole' : 'holes'} left. Ringed in red.`,
    showHoles: 'Show holes  H',
    doneBlocked: (n) => `Needs 100% — ${n} ${n === 1 ? 'pixel' : 'pixels'} empty`,
    donePlace: (roles) => `Place: ${roles}`,
    clear: 'Clear canvas',
    clearConfirm: 'Clear it?',
    deleteConfirm: 'Delete it?',
    roles: (placed, total) => `Roles · ${placed} / ${total} placed`,
    rolePlace: 'click canvas',
    rolePlaced: 'placed',
    roleRequired: 'required',
    roleOptional: 'optional',
    rolesNote: 'Points pull the pixels around them. Nothing gets cut.',
    rolesMissing: 'Place all required points to see the full cycle',
    clearRig: 'Clear rig',
    previewCap: (behaviour) => `Live — ${behaviour} cycle`,
    mesh: 'Mesh',
    speed: 'Speed',
    paused: 'Paused — press play',
    fps: (n) => `${n} fps`,
    fpsFallback: (n, cols, rows) => `${n} fps · mesh ${cols}×${rows}`,
    behaviours: { walk: 'Walk', fly: 'Fly', jump: 'Hop', spin: 'Spin', idle: 'Idle' },
    sound: 'Sound',
    record: '● Record',
    recording: (s) => `● Recording ${s}s`,
    play: '▶ Play',
    delete: '⌫ Delete',
    soundNote: 'One short mono take. 1.5 seconds, max.',
    soundTime: (now, max) => `${now} s / ${max} s`,
    noMic: 'No microphone access. Sound is optional — skip it.',
    tools: {
      brush: 'Brush',
      eraser: 'Eraser',
      fill: 'Fill',
      picker: 'Eyedropper',
      mirror: 'Mirror mode',
      pixel: 'Pixel art',
      undo: 'Undo',
      redo: 'Redo',
      clear: 'Clear',
    },
    skip: 'Skip to canvas',
    canvasNote: 'Drawing needs a pointer. Rig points can be placed from the role list with the keyboard.',
  },
};
